# Find all properties whose domain is either Conference or Journal

PREFIX sdm: <http://www.semanticweb.org/emmasalvan/ontologies/2022/4/sdmlab3#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?property
WHERE {
    {?property rdfs:domain sdm:Conference}
        UNION
    {?property rdfs:domain sdm:Journal}
}
