name: Build RDFS with nix
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build_rdfs_artifact:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v10
      with:
        name: leixb
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
    - name: Build image
      run: nix build -L .#rdfs -o abox.owl

    - name: Copy tbox.owl to root
      run: cp src/main/resources/sdmlab3.owl tbox.owl

    - uses: actions/upload-artifact@v3
      with:
        name: deliverable
        path: |
          tbox.owl
          abox.owl
          pom.xml
          src
          data
          process_all.sh


